name: Run Kotlin Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Kotlin Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Tests in Specific Folder
        run: |
          # Verify Gradle wrapper exists
          if [ ! -f ./gradlew ]; then
            echo "Gradle wrapper not found. Generating Gradle wrapper..."
            gradle wrapper
          fi

          # Ensure the Gradle wrapper is executable
          chmod +x ./gradlew

          # Run tests only in the test/kotlin/easy folder
          ./gradlew test --tests "easy.*"
